export interface PhoneDescr {
	id: string,
	namespaceId: string,
	name: string,
	capacityAvailable: string[],
	capacity: string,
	priceRegular: number,
	priceDiscount: number,
	colorsAvailable: string[],
	color: string,
	images: string[],
	description: JSON[],
	screen: string,
	resolution: string,
	processor: string,
	ram: string,
	camera: string,
	zoom: string,
	ceil: string[],
}
